### ISSUE TITLE
compilation error: cannot convert argument LPSTR to LPCWSTR

### ISSUE THREAD

**Issue by ThatGamerBlue** [makemek/cheatengine-threadstack-finder#1]
http://i.imgur.com/VTFgNWh.png

**Comment by makemek** [comment]
Please compile it with x86 build configuration

**Comment by Lauriy** [comment]
[threadstack.zip](https://github.com/makemek/cheatengine-threadstack-finder/files/685703/threadstack.zip)

Compiled on W10, maybe of some help to people who don't want to waste 10 GB on VS.
