### ISSUE TITLE
How to Get ThreadStack# for 64bit Program?

### ISSUE THREAD

**Issue by Acidic9** [makemek/cheatengine-threadstack-finder#2]
In the README.md file, it states that the code only works for 32bit processors.
How can this code be used for 64bit?

---

**I LOVE YOU FOR MAKING THAT POST ON CHEATENGINE FORUMS AND EXPLAINING EVERY SINGLE THING ABOUT THREADSTACK AND HOW TO USE IT IN C++**

**Comment by makemek** [comment]
Wow, thanks 😄 .

Changing [buffer size](https://github.com/makemek/cheatengine-threadstack-finder/blob/thread-base-addr/main.cpp#L128) from 4096 to 8192 is likely a possible solution.
I tried it, but still doesn't work.
I'm sure that to make it work in 64-bit, I have to make change in those code section.
But it is a lot more tricky than I expected.

It has been 2 years and I rarely maintain this project anymore.
I have no plan to make it work with 64 bit app at the moment.

PR is always welcome.
