### ISSUE TITLE
Can you please post a compiled exe/dll?

### ISSUE THREAD

**Issue by DarkTussin** [makemek/cheatengine-threadstack-finder#3]
Hey, I appreciate you posting this - I'm having some trouble compiling it.

Can you please post a compiled executable or dll?

It would be easy enough to wrap the exe for what I need to do - thanks.

Edit: Got it compiling - showing all 0's for base addresses (it's a 32 bit process on a 64 bit system).

I tried running in cmd as administrator - no dice unfortunately.

On the plus side, it is showing the same threadID's as my C# program - going to keep playing with it

**Comment by Delthas** [comment]
Could you post the compiled executable? I can't get to compile it either and I'd rather grab an exe than spending some time making it compile on my machine. @DarkTussin

**Comment by makemek** [comment]
@Lauriy has already made a compiled version in #1.
Please take a look.
There's only executable available.

For dll, there is `dll-export` branch in this repo.
I may create a compiled dll if you prefer.

**Comment by Delthas** [comment]
I just needed the exe. Thanks!

**Comment by DarkTussin** [comment]
Awesome! Thanks so much for your replies :)

It seems to be working and it's returning base addresses now!

I really appreciate it!
