### ISSUE TITLE
something went wrong when i debugged the program

### ISSUE THREAD

**Issue by Natuki1** [makemek/cheatengine-threadstack-finder#4]
there is no problem when i use the threadstack.exe you have already compiled ;
but when i was attempted to debug the cpp i found my BASE ADDRESS is 0x00000000, i am sure my process is 32-bit and it works when i use  threadstack.exe you have already compiled.
i search for the problem for a long time and finally,i find that  this line has problem
if (buf32[i] >= (DWORD)mi.lpBaseOfDll && buf32[i] <= (DWORD)mi.lpBaseOfDll + mi.SizeOfImage)
![image](https://user-images.githubusercontent.com/73566623/110910316-1e0f3b80-834c-11eb-96ad-525335d07f3c.png)
you know why?cause DWORD can not deal with a value over 4294967295!
![image](https://user-images.githubusercontent.com/73566623/110910832-d4732080-834c-11eb-8afe-6a87d6a8ee87.png)
but then i cope with the problem by using stringstream and unsigned long long,in this way,it will assure the length of the value,so that it will not overflow，
after finishing all the work ,it comes out the value that seems to be right,but i compare the BASE ADDRESS  where the program is changed by me with the right BASE ADDRESS where acts on the threadstack.exe you have already compiled,i find my BASE ADDRESS is not right,although it is not  0x00000000
i hope you can reply me,i am a chinese student and my english is not so good,but the problem has troubled me for several days,there is no valuable information online,so i have to turn to you!
my email is 2534765682@@qq.com

**Comment by makemek** [comment]
It could be that you compiled the source code as x64 executable.
Please compile it as an x86 executable.

This video might help you
https://youtu.be/YDHE42QIRNQ?t=121

**Comment by Natuki1** [comment]
Thanks for your help，sincerely！
